name: ftools
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - bwa
  - blast
  - seqtk
  - samtools
  - ncurses
  - bamtools
  - bcftools
  - vcftools
  - MUSCLE
  - FastTree
  - vcfkit
  - tabix
